server:
  port: 1234
spring:
  application:
    name: micro-service-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chensir2896/micro-service-share-config    #配置git仓库地址
          search-paths: /                                                 #配置仓库路径的相对路径，可以填写多个
#          username:                                                         #访问git仓库的用户名  Git仓库为公开仓库，可以不填写用户名和密码，如果是私有仓库需要填写
#          password:                                                         # 问git仓库的用户密码
      label: master                                                         #配置仓库的分支
